PPAttendanceSystem/PPAttendanceSystem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _5051.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin Dashboard landing page
        public ActionResult AdminDashboard()
        {
            ViewBag.Message = "Admin Dashboard";

            return View();
        }

        // GET: Admin Dashboard landing page (different week view)
        public ActionResult AdminDashboardp1()
        {
            ViewBag.Message = "Admin Dashboard (-1wk)";

            return View();
        }

        // GET: Admin Dashboard landing page (different week view)
        public ActionResult AdminDashboardp2()
        {
            ViewBag.Message = "Admin Dashboard (-2wk)";

            return View();
        }

        // GET: Admin Dashboard landing page (different view specific to Monday)
        public ActionResult AdminDashboardm()
        {
            ViewBag.Message = "Admin Dashboard Monday";

            return View();
        }

        // GET: Admin Dashboard landing page (different view specific to Wednesday)
        public ActionResult AdminDashboardw()
        {
            ViewBag.Message = "Admin Dashboard Wednesday";

            return View();
        }

        // GET: Class Roster
        public ActionResult ClassRoster()
        {
            ViewBag.Message = "Class Roster";

            return View();
        }
        
        // GET: Admin report on class community hours goal
        public ActionResult CommunityHours()
        {
            ViewBag.Message = "Community Hours";

            return View();
        }
        
        // GET: Admin calendar
        public ActionResult SchoolCalendar()
        {
            ViewBag.Message = "School Calendar";

            return View();
        }
        
        // GET: Custom Report
        public ActionResult CustomReport()
        {
            ViewBag.Message = "Build Custom Reports";

            return View();
        }
        
        // GET: Admin custom report (all class)
        public ActionResult CustomReportResult()
        {
            ViewBag.Message = "Custom Report";

            return View();
        }
        
        // GET: Admin custom report (individual student)
        public ActionResult CustomReportIndividualResult()
        {
            ViewBag.Message = "Custom Individual Report";

            return View();
        }
        
        // GET: Class settings page
        public ActionResult ClassSettings()
        {
            ViewBag.Message = "Class Settings";

            return View();
        }

        // GET: Student Change Log for custom edits
        public ActionResult StudentChangeLog()
        {
            ViewBag.Message = "Student Change Log";

            return View();
        }
    }
}

PPAttendanceSystem/PPAttendanceSystem/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _5051.Controllers
{
    public class LandingController : Controller
    {
        // GET: Landing
        public ActionResult Home()
        {
            ViewBag.Message = "Home";
            return View();
        }

    }
}

PPAttendanceSystem/PPAttendanceSystem/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _5051.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Student profile home page
        public ActionResult StudentHome()
        {
            ViewBag.Message = "Student Home";

            return View();
        }

        // GET: Student profile report page
        public ActionResult StudentReport()
        {
            ViewBag.Message = "Student Report";

            return View();
        }

        // GET: Student profile edit page
        public ActionResult StudentEdit()
        {
            ViewBag.Message = "Student Edit";

            return View();
        }
    }
}

PPAttendanceSystem/PPAttendanceSystem/Controllers/StudentController.cs
using System.Web.Mvc;
using _5051.Models;
using _5051.Backend;

namespace _5051.Controllers
{
    public class StudentController : Controller
    {

        // A ViewModel used for the Student that contains the StudentList
        private StudentViewModel StudentViewModel = new StudentViewModel();

        // The Backend Data source
        private StudentBackend StudentBackend = StudentBackend.Instance;

        // GET: Student
        /// <summary>
        /// Index, the page that shows all the Students
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // Load the list of data into the StudentList
            var myDataList = StudentBackend.Index();
            var StudentViewModel = new StudentViewModel(myDataList);
            return View(StudentViewModel);
        }

        // GET: Puzzle page
        public ActionResult Puzzle()
        {
            ViewBag.Message = "Puzzle";

            return View();
        }

        /// <summary>
        /// Read information on a single Student
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Student/Details/5
        public ActionResult Read(string id = null)
        {
            var myDataStudent = StudentBackend.Read(id);
            if (myDataStudent == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var myData = new StudentDisplayViewModel(myDataStudent);
            if (myData == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(myData);
        }

        /// <summary>
        /// This opens up the make a new Student screen
        /// </summary>
        /// <returns></returns>
        // GET: Student/Create
        public ActionResult Create()
        {
            var myData = new StudentModel();
            return View(myData);
        }

        /// <summary>
        /// Make a new Student sent in by the create Student screen
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: Student/Create
        [HttpPost]
        public ActionResult Create([Bind(Include=
                                        "Id,"+
                                        "Name,"+
                                        "Description,"+
                                        "Uri,"+
                                        "AvatarId,"+
                                        "Status,"+
                                        "Tokens,"+
                                        "ExperiencePoints,"+
                                        "AvatarLevel,"+
                                        "")] StudentModel data)
        {
            if (!ModelState.IsValid)
            {
                // Send back for edit
                return View(data);
            }

            if (data == null)
            {
                // Send to Error Page
                return RedirectToAction("Error", new { route = "Home", action = "Error" });
            }

            if (string.IsNullOrEmpty(data.Id))
            {
                // Return back for Edit
                return View(data);
            }

            StudentBackend.Create(data);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// This will show the details of the Student to update
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Student/Edit/5
        public ActionResult Update(string id = null)
        {
            var myDataStudent = StudentBackend.Read(id);
            if (myDataStudent == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var myData = new StudentDisplayViewModel(myDataStudent);
            if (myData == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(myData);
        }

        /// <summary>
        /// This updates the Student based on the information posted from the udpate page
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        // POST: Student/Update/5
        [HttpPost]
        public ActionResult Update([Bind(Include=
                                        "Id,"+
                                        "Name,"+
                                        "Description,"+
                                        "Uri,"+
                                        "AvatarId,"+
                                        "AvatarLevel,"+
                                        "Tokens,"+
                                        "Status,"+
                                        "ExperiencePoints,"+
                                        "Password,"+
                                        "Tokens,"+
                                        "")] StudentDisplayViewModel data)
        {
            if (!ModelState.IsValid)
            {
                // Send back for edit
                return View(data);
            }

            if (data == null)
            {
                // Send to Error Page
                return RedirectToAction("Error", new { route = "Home", action = "Error" });
            }

            if (string.IsNullOrEmpty(data.Id))
            {
                // Send back for edit
                return View(data);
            }

            var myDataStudent = new StudentModel(data);
            StudentBackend.Update(myDataStudent);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// This shows the Student info to be deleted
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Student/Delete/5
        public ActionResult Delete(string id = null)
        {
            var myDataStudent = StudentBackend.Read(id);
            if (myDataStudent == null)
            {
                RedirectToAction("Error", "Home");
            }

            var myData = new StudentDisplayViewModel(myDataStudent);
            if (myData == null)
            {
                RedirectToAction("Error", "Home");
            }

            return View(myData);
        }

        /// <summary>
        /// This deletes the Student sent up as a post from the Student delete page
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete([Bind(Include=
                                        "Id,"+
                                        "Name,"+
                                        "Description,"+
                                        "AvatarId,"+
                                        "Uri,"+
                                        "Status,"+
                                        "Tokens,"+
                                        "ExperiencePoints,"+
                                        "AvatarLevel,"+
                                        "")] StudentDisplayViewModel data)
        {
            if (!ModelState.IsValid)
            {
                // Send back for edit
                return View(data);
            }
            if (data == null)
            {
                // Send to Error page
                return RedirectToAction("Error", new { route = "Home", action = "Error" });
            }

            if (string.IsNullOrEmpty(data.Id))
            {
                // Send back for Edit
                return View(data);
            }

            StudentBackend.Delete(data.Id);

            return RedirectToAction("Index");
        }
    }
}

PPAttendanceSystem/PPAttendanceSystem/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--
	Document Title
	=============================================
	-->
	<link rel="shortcut icon" href="~/Content/Landing/wayfinder-icon.ico">
	<title>Wayfinder | @ViewBag.Title</title>

	<!--
	Stylesheets
	=============================================
	-->
	<link href="~/Content/Landing/css/style.css" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/Content/Site.css" rel="stylesheet">
	<link href="~/Content/dropbtn.css" rel="stylesheet">
	<link href="@Url.Content("~/Content/StudentDashBoard.css")" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


	<script>
		$(function () {
			var dateFormat = "mm/dd/yy",
				from = $("#from")
					.datepicker({
						defaultDate: "+1w",
						changeMonth: true,
						numberOfMonths: 3
					})
					.on("change", function () {
						to.datepicker("option", "minDate", getDate(this));
					}),
				to = $("#to").datepicker({
					defaultDate: "+1w",
					changeMonth: true,
					numberOfMonths: 3
				})
					.on("change", function () {
						from.datepicker("option", "maxDate", getDate(this));
					});

			function getDate(element) {
				var date;
				try {
					date = $.datepicker.parseDate(dateFormat, element.value);
				} catch (error) {
					date = null;
				}

				return date;
			}
		});
	</script>

    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            var data = google.visualization.arrayToDataTable([
                ['Emotion Tracker', 'Frequency %'],
                ['Very Sad', 24],
                ['Sad', 11],
                ['Indifferent', 45],
                ['Happy', 10],
                ['Very Happy', 10]
            ]);

            var options = {
                title: 'Class Emotion Tracker',
                backgroundColor: 'transparent'


            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));

            chart.draw(data, options);
        }
    </script>  






    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Emotion Tracker', 'Frequency %'],
                ['Completed', 60],
                ['Remaining', 40],

            ]);

            var options = {
                pieHole: 0.4,
                color: 'white',
                backgroundColor: 'transparent',
                title: 'Community Hours Tracker'
            };

            var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
            chart.draw(data, options);
        }
    </script>

    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawVisualization);

        function drawVisualization() {
            var data = google.visualization.arrayToDataTable([
                ['Time Frame', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                ['5/21-25', 8, 6, 8, 4, 8],
                ['5/28-6/1', 8, 5, 4, 8, 8]

            ]);

            var options = {
                title: 'Attendance Tracker',
                vAxis: { title: 'Hours' },
                hAxis: { title: 'Time' },
                seriesType: 'bars',
                backgroundColor: 'transparent',
                series: { 5: { type: 'line' } }
            };

            var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
            chart.draw(data, options);
        }
    </script>

    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            var data = google.visualization.arrayToDataTable([
                ['Emotion Tracker', 'Frequency %'],
                ['Very Sad', 10],
                ['Sad', 20],
                ['Indifferent', 40],
                ['Happy', 20],
                ['Very Happy', 10]
            ]);

            var options = {
                title: 'Emotions Tracker',
                backgroundColor: 'transparent'


            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));

            chart.draw(data, options);
        }
    </script>

    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {


            var data = google.visualization.arrayToDataTable([
                ['Time Frame', 'Attendance', 'Emotions'],
                ['5/21', 8, 3],
                ['5/22', 6, 3],
                ['5/23', 8, 1],
                ['5/24', 4, 2],
                ['5/25', 8, 4,],
                ['5/228', 8, 3],
                ['5/29', 5, 3],
                ['5/230', 4, 2],
                ['5/31', 8, 5,],
                ['6/1', 8, 4]
            ]);


            var options = {
                title: 'Emotions. vs. Attendance',
                curveType: 'function',
                backgroundColor: 'transparent',
                legend: { position: 'bottom' }

            };

            var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

            chart.draw(data, options);
        }
    </script>






	<!-- navbar links-->
	<div class="container-fluid shared-head">
		<div class="row">
			<div class="col-md-6">
				<img src="~/Content/Landing/logo.png">
			</div>
			<div class="col-md-6 menu">
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")">Home</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")#kiosk">Kiosk</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("AdminDashboard", "Admin")">Admin</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("ClassSettings", "Admin")">Settings</a></div>
			</div>
		</div>
	</div>
</head>

<body>
	<!-- Don't delete this or else MVC gets very angry-->
	<div class="container">
		@RenderBody()
	</div>

	<!-- JQuery and JavaScript-->
	<script type="text/javascript" src="~/Scripts/tableContent.js"></script>

	<script type="text/javascript" src="~/Scripts/bootstrap-clockpicker.js"></script>
	<script type="text/javascript" src="~/Scripts/clockpicker.js"></script>
	<script type="text/javascript" src="~/Scripts/highlight.min.js"></script>
	<script type="text/javascript" src="~/Scripts/jquery-clockpicker.js"></script>
	<script src="~/Scripts/time.js"></script>
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/studentDashboard")
</body>
</html>

PPAttendanceSystem/PPAttendanceSystem/Views/Shared/_KioskLayout.cshtml
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--
	Document Title
	=============================================
	-->
	<link rel="shortcut icon" href="~/Content/Landing/wayfinder-icon.ico">
	<title>Wayfinder | @ViewBag.Title</title>

	<!--
	Stylesheets
	=============================================
	-->
	<link href="~/Content/Landing/css/style.css" rel="stylesheet">
	<link href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/Content/Site.css" rel="stylesheet">
	<link href="@Url.Content("~/Content/StudentDashBoard.css")" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">


	<!-- navbar links-->
	<div class="container-fluid shared-head">
		<div class="row">
			<div class="col-md-7">
				<img src="~/Content/Landing/logo.png">
			</div>
			<div class="col-md-5 menu">
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")">Home</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")#admin">Admin</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Index", "Student")">Dashboard</a></div>
				<div class="col-md-3"><a href="@Url.Action("Create", "Student")"><button class="btn btn-light head-btn-circle glyphicon-plus" type="button"></button></a></div>
			</div>
		</div>
	</div>
</head>

<body>


    <!-- Don't delete this or else MVC gets very angry-->
    <div class="container">
        @RenderBody()
    </div>


        <!-- JQuery and JavaScript-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/studentDashboard")
</body>
</html>

PPAttendanceSystem/PPAttendanceSystem/Views/Shared/_LandingLayout.cshtml
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--
	Document Title
	=============================================
	-->
	<link rel="shortcut icon" href="~/Content/Landing/wayfinder-icon.ico">
	<title>Wayfinder | Welcome</title>

	<!--
	Stylesheets
	=============================================
	-->
	<!-- Default stylesheets-->
	<link href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<!-- Template specific stylesheets-->
	<link href="http://weloveiconfonts.com/api/?family=fontawesome" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
	<link href="~/assets/lib/animate.css/animate.css" rel="stylesheet">
	<link href="~/assets/lib/components-font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="~/assets/lib/et-line-font/et-line-font.css" rel="stylesheet">
	<link href="~/assets/lib/flexslider/flexslider.css" rel="stylesheet">
	<link href="~/assets/lib/owl.carousel/dist/assets/owl.carousel.min.css" rel="stylesheet">
	<link href="~/assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css" rel="stylesheet">
	<link href="~/assets/lib/magnific-popup/dist/magnific-popup.css" rel="stylesheet">
	<link href="~/assets/lib/simple-text-rotator/simpletextrotator.css" rel="stylesheet">
	<!-- Main stylesheet and color file-->
	<link href="~/Content/Landing/css/style.css" rel="stylesheet">
	<link id="color-scheme" href="~/Content/Landing/css/colors/default.css" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
	<main>
		<!-- Loading animation-->
		<div class="page-loader">
			<div class="loader">Loading...</div>
		</div>

		<!-- Navbar-->
		<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>		
					<div>
						<img src="~/Content/Landing/wayfinder-logo.png" height="50" width="50" style="padding-top:10px; padding-right:10px; float:left"/>
						<a class="navbar-brand" href="@Url.Action("Home", "Landing")">Wayfinder</a>
					</div>
				</div>
				<div class="collapse navbar-collapse" id="custom-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a class="dropdown-toggle" href="#" data-toggle="dropdown">Home</a>
							<ul class="dropdown-menu">
								<li><a href="#kiosk">Course Kiosk</a></li>
								<li><a href="#admin">Admin Portal</a></li>
								<li><a href="#student">Student Portal</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<!-- I don't know why, but deleting this makes the CSS angry and ugly-->
		</div>

		<!-- Scroll up button-->
		<div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>
	</main>

	<!-- Also don't delete this or else MVC gets very angry-->
        @RenderBody()



	<!--
	JavaScripts
	=============================================
	-->
	<script src="~/assets/lib/jquery/dist/jquery.js"></script>
	<script src="~/assets/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="~/assets/lib/wow/dist/wow.js"></script>
	<script src="~/assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js"></script>
	<script src="~/assets/lib/isotope/dist/isotope.pkgd.js"></script>
	<script src="~/assets/lib/imagesloaded/imagesloaded.pkgd.js"></script>
	<script src="~/assets/lib/flexslider/jquery.flexslider.js"></script>
	<script src="~/assets/lib/owl.carousel/dist/owl.carousel.min.js"></script>
	<script src="~/assets/lib/smoothscroll.js"></script>
	<script src="~/assets/lib/magnific-popup/dist/jquery.magnific-popup.js"></script>
	<script src="~/assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js"></script>
	<script src="~/assets/js/plugins.js"></script>
	<script src="~/assets/js/main.js"></script>
</body>
</html>

PPAttendanceSystem/PPAttendanceSystem/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--
	Document Title
	=============================================
	-->
	<link rel="shortcut icon" href="~/Content/Landing/wayfinder-icon.ico">
	<title>Wayfinder | @ViewBag.Title</title>

	<!--
	Stylesheets
	=============================================
	-->
	<link href="~/Content/Landing/css/style.css" rel="stylesheet">
	<link href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/Content/Site.css" rel="stylesheet">
	<link href="@Url.Content("~/Content/StudentDashBoard.css")" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


	<!-- navbar links-->
	<div class="container-fluid shared-head">
		<div class="row">
			<div class="col-md-8">
				<img src="~/Content/Landing/logo.png">
			</div>
			<div class="col-md-4 menu">
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")">Home</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")#kiosk">Kiosk</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("Home", "Landing")#admin">Admin</a></div>
				<div class="col-md-3"><a class="btn btn-link head-btn" href="@Url.Action("StudentHome", "Profile")">Student</a></div>
			</div>
		</div>
	</div>

	<!-- Donut chart-->
	<script type="text/javascript">
		google.charts.load("current", { packages: ["corechart"] });
		google.charts.setOnLoadCallback(drawChart);
		function drawChart() {
			var data1 = google.visualization.arrayToDataTable([
				['Attendance Type', 'Frequency %'],
				['Excused', 10],
				['Missed', 15],
				['Partial day', 40],
				['Full day', 35]
			]);

			var options1 = {
				width: 600,
				height: 340,
				pieHole: 0.4,
				backgroundColor: 'transparent',
				color: 'white',
				title: 'Annual Attendance'
			};

			var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
			chart.draw(data1, options1);
		}
	</script>
	<!-- Bar chart-->
	<script type="text/javascript">
		google.charts.load("current", { packages: ["corechart"] });
		google.charts.setOnLoadCallback(drawChart);
		function drawChart() {
			var data2 = google.visualization.arrayToDataTable([
				['Mood', 'Frequency', { role: 'style' }],
				['Sadder', 29, '#FFEA53'],
				['Neutral', 46, '#5378FF'],
				['Happier', 25, '#9453FF'],
			]);

			var options2 = {
				title: "Mood Frequency (Annual)",
				backgroundColor: 'transparent',
				legend: { position: "none" },
				titleTextStyle:
					{
						color: 'Black'
					},
			};

			var chart = new google.visualization.BarChart(document.getElementById('barchart_values'));
			chart.draw(data2, options2);
		}
	</script>
</head>

<body>


    <!-- Don't delete this or else MVC gets very angry-->
    <div class="container">
        @RenderBody()
    </div>

    <!-- JQuery and JavaScript-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/studentDashboard")
</body>
</html>